name: ParseMultipleFiles
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:    
      - name: Get current date
        id: date
        run: |
          echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
          echo ${{ env.NOW }}
      - name: Cache DateTime
        if: github.event_name == 'push'
        uses: actions/cache@v1
        with:
          path: DateTime
          key: datetime-${{ GITHUB_ENV }}-${{ github.event.number }}-{{ github.sha }}
          restore-keys: |
              datetime-${{ github.event_name }}-${{ github.event.number }}
      


    
