name: ParseMultipleFiles
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
 Build:
    runs-on: windows-latest
    steps:  
    
      - uses: actions/checkout@v2
      - name: create temp file
        run: |
                $files = Get-ChildItem -Path ${{ github.workspace }}\MyProject -Recurse -Filter project.json -File
                foreach($package in Get-ChildItem -Path ${{ github.workspace }}\MyProject -Recurse -Filter project.json -File)
                       {    
                           if($package.Name -match 'project.json')
                           {
                              $PATH = $package.FullName
                           }
                       }
                       
                    
      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
         format: YYMMDDHHmm
         utcOffset: "+08:00"
         
         
      - name: Use current time
        env:
         MAJOR: 1
         MINOR: 0
         F_TIME: "${{ steps.current-time.outputs.formattedTime }}"
        run: |
          echo ${{env.MAJOR}}.${{env.MINOR}}.${{env.BUILD}}.${{env.F_TIME}}
          
          
          
      - name: GetVersionFromJson
        id: version
        uses: notiz-dev/github-action-json-property@release
        with: 
           path: 'project.json'
           prop_path: 'projectVersion'
           if: github.ref == 'refs/heads/main'
      - run: echo ${{steps.version.outputs.prop}}
      
          
      
      - name: Version Incrment
        id: vars
        env:
            VERSION: ${{steps.version.outputs.prop}}
        run: |
               $v= [version] "${{steps.version.outputs.prop}}"
               $newversion= "{0}.{1}.{2}.{3}" -f $v.Major, $v.Minor, ($v.Build+1),"${{ steps.current-time.outputs.formattedTime }}"
               $VERSION=[string]$newversion
               echo $VERSION 
               

    
          
          
                         

      - uses: actions/checkout@v2
      - run: |
                 New-Item -Path "C:\\" -ItemType "directory" -Name "uipathcli";
                 Invoke-WebRequest "https://www.myget.org/F/uipath-dev/api/v2/package/UiPath.CLI/1.0.7758.25166" -OutFile "C:\\uipathcli\\cli.zip";
                 Expand-Archive -LiteralPath "C:\\uipathcli\\cli.Zip" -DestinationPath "C:\\uipathcli"; 
                 
                 
           
                
      - name: shellcheck 
        shell: cmd
        run: |
               call "C:\\uipathcli\\lib\\net461\\uipcli.exe" package pack "${{ github.workspace }}\MyProject" -o "${{ github.workspace }}" -v "1.0.5.2563452" -l en-US
     
     
     
     
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.0
        with:	 
             name: samplerepository
             path: ${{ github.workspace }}/**
             if-no-files-found: error
             retention-days: 90
             
             
             
             
             
      - name: Download Artifacts
        uses: actions/download-artifact@v2.0.9
        with:
            name: 'samplerepository'
            path: 'samplerepository'

