name: ParseMultipleFiles
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
 Build:
    runs-on: windows-latest
    steps:  
      - uses: actions/checkout@v2
      - run: |
                 New-Item -Path "C:\\" -ItemType "directory" -Name "uipathcli";
                 Invoke-WebRequest "https://www.myget.org/F/uipath-dev/api/v2/package/UiPath.CLI/1.0.7758.25166" -OutFile "C:\\uipathcli\\cli.zip";
                 Expand-Archive -LiteralPath "C:\\uipathcli\\cli.Zip" -DestinationPath "C:\\uipathcli"; 
                 
                 
           
                
      - name: shellcheck 
        shell: cmd
        run: |
               call "C:\\uipathcli\\lib\\net461\\uipcli.exe" package pack "${{ github.workspace }}\MyProject" -o "${{ github.workspace }}" -v "1.0.5.2563452" -l en-US
     
     
     
     
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.0
        with:	 
             name: samplerepository
             path: ${{ github.workspace }}/**
             if-no-files-found: error
             retention-days: 90
             
             
             
             
             
      - name: Download Artifacts
        uses: actions/download-artifact@v2.0.9
        with:
            name: 'samplerepository'
            path: 'samplerepository'

