name: ParseMultipleFiles
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
 Build:
    runs-on: windows-latest
    steps:   
      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
         format: YYMMDDHHmm
         utcOffset: "+08:00"
         
         
      - name: Use current time
        id: vars
        env:
         F_TIME: "${{ steps.current-time.outputs.formattedTime }}"
        run: |
          echo ${{env.MAJOR}}.${{env.MINOR}}.${{env.BUILD}}.${{env.F_TIME}} 
          echo "::set-output name=version::$(echo '${{env.MAJOR}}.${{env.MINOR}}.${{env.BUILD}}.${{env.F_TIME}}')"
          
          
          
          
      - uses: actions/checkout@v2
      - name: create temp file
        run: |
                $files = Get-ChildItem -Path ${{ github.workspace }}\MyProject -Recurse -Filter project.json -File
                foreach($package in Get-ChildItem -Path ${{ github.workspace }}\MyProject -Recurse -Filter project.json -File)
                       {    
                           if($package.Name -match 'project.json')
                           {
                              $PATH = $package.FullName
                           }
                       }
                       
                       

      - uses: actions/checkout@v2
      - run: |
                 New-Item -Path "C:\\" -ItemType "directory" -Name "uipathcli";
                 Invoke-WebRequest "https://www.myget.org/F/uipath-dev/api/v2/package/UiPath.CLI/1.0.7758.25166" -OutFile "C:\\uipathcli\\cli.zip";
                 Expand-Archive -LiteralPath "C:\\uipathcli\\cli.Zip" -DestinationPath "C:\\uipathcli"; 
                 
                 
           
                
      - name: shellcheck 
        shell: cmd
        run: |
               call "C:\\uipathcli\\lib\\net461\\uipcli.exe" package pack "${{ github.workspace }}\MyProject" -o "${{ github.workspace }}" -v "${{steps.vars.outputs.version}}" -l en-US
     
     
     
     
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.0
        with:	 
             name: samplerepository
             path: ${{ github.workspace }}/**
             if-no-files-found: error
             retention-days: 90
             
             
             
             
             
      - name: Download Artifacts
        uses: actions/download-artifact@v2.0.9
        with:
            name: 'samplerepository'
            path: 'samplerepository'

