name: ParseMultipleFiles
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:    
      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
         format: YYMMDDHHmm
         utcOffset: "+08:00"
      - name: Use current time
        env:
         MAJOR: 1
         MINOR: 0
         BUILD: ${{github.run_number}}
         TIME: "${{ steps.current-time.outputs.time }}"
         R_TIME: "${{ steps.current-time.outputs.readableTime }}"
         F_TIME: "${{ steps.current-time.outputs.formattedTime }}"
         YEAR: "${{ steps.current-time.outputs.year }}"
         DAY: "${{ steps.current-time.outputs.day }}"
        run: |
          echo ${{env.MAJOR}}.${{env.MINOR}}.${{env.BUILD}}.${{env.F_TIME}}

      - name: create temp file
        run: |
               Get-ChildItem -Path ${{ github.workspace }}\MyProject -Recurse -Filter *.json -Directory | 
               foreach {
               
                         console.log($_.FullName)
                         if((Get-Content $_.FullName) -match 'project')
                            {
                               Folder =$_.FullName
                               echo Folder
                            }
                       }
                

    
         
      
          


    
