name: ParseMultipleFiles
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
 Build:
    runs-on: windows-latest
    steps:   
      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
         format: YYMMDDHHmm
         utcOffset: "+08:00"
      - name: Use current time
        env:
         MAJOR: 1
         MINOR: 0
         BUILD: ${{github.run_number}}
         TIME: "${{ steps.current-time.outputs.time }}"
         R_TIME: "${{ steps.current-time.outputs.readableTime }}"
         F_TIME: "${{ steps.current-time.outputs.formattedTime }}"
         YEAR: "${{ steps.current-time.outputs.year }}"
         DAY: "${{ steps.current-time.outputs.day }}"
        run: |
          echo ${{env.MAJOR}}.${{env.MINOR}}.${{env.BUILD}}.${{env.F_TIME}}
          
      - uses: actions/checkout@v2
      - name: create temp file
        run: |
                foreach($package in Get-ChildItem -Path ${{ github.workspace }}\MyProject -Recurse -Filter project.json -File)
                       {    
        if: ${{package.Name}} =='project.json'
      - name: GetVersionFromJson
        id: version
        uses: notiz-dev/github-action-json-property@release
        with: 
           path: $package.Name
           prop_path: 'projectVersion'
      - run: echo ${{steps.version.outputs.prop}} 
                       }
