name: ParseMultipleFiles
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:    
      - name: Get current date
        id: date
        run: echo "NOW=$(date +'DateTime.Now.TryParseExact(s,"yyyyMMdd",CultureInfo.InvariantCulture,DateTimeStyles.AssumeUniversal,out result)')" >> $GITHUB_ENV
      
      - name: Test with environment variables
        run: echo ${{ env.NOW }}
             
      


    
