name: ParseMultipleFiles
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:    
      - name: Get current date
        env:
            NOW: 0
        id: date
        run: |
               string s = Datetime.Now;
       
               echo s
      
      


    
