name: ParseMultipleFiles
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:    
      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
         format: YYMMDDHHmm
         utcOffset: "+08:00"
        env:
         TIME: "${{ steps.current-time.outputs.time }}"
         R_TIME: "${{ steps.current-time.outputs.readableTime }}"
         F_TIME: "${{ steps.current-time.outputs.formattedTime }}"
      


    
