name: ParseMultipleFiles
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:    
      - name: Get current date
        id: date
        run: |
          mkdir DateTime
          echo $(date '+%H:%M:%S') > DateTime/DateTime.txt
          cat DateTime/DateTime.txt
      - name: Cache DateTime
        if: github.event_name == 'pull_request'
        uses: actions/cache@v1
        with:
          path: DateTime
          key: datetime-${{ github.event_name }}-${{ github.event.number }}-{{ github.sha }}
          restore-keys: |
           datetime-${{ github.event_name }}-${{ github.event.number }}
      - name: Compare DateTime
             
      


    
