name: ParseMultipleFiles
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:    
      - name: Get current date
        env:
            NOW: 0
        id: date
        run: |
          echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
          echo ${{ env.NOW }}
      
      


    
