name: ParseMultipleFiles
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:    
      - name: Get current date
        env:
            NOW: 0
        id: date
        run: |
               $env.NOW = !DateTime.TryParseExact(s,"yyyyMMdd",CultureInfo.InvariantCulture,DateTimeStyles.AssumeUniversal,out result)
               echo $env.NOW
      
      


    
