name: ParseMultipleFiles
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
 Build:
    runs-on: windows-latest 
    steps:   
      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
         format: YYMMDDHHmm
         utcOffset: "+08:00"
      - name: Use current time
        env:
         F_TIME: "${{ steps.current-time.outputs.formattedTime }}"         
        run: |
          echo ${{env.F_TIME}}
      - uses: actions/checkout@v2
      - name: Parse Files
        id: Parse
        run: |
                foreach($package in Get-ChildItem -Path ${{ github.workspace }}\MyProject -Recurse -Filter project.json -File)
                {
                  echo ::set-output name=PATH_VALUE::$package
                }
        env: 
            PATH: ${{steps.Parse.outputs.PATH_VALUE}}
