name: Path lister
on: [push]
jobs:
  list:
    name: Path lister
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v1
      - name: Fetch action
        id: pl
        uses: Rishabh510/Path-lister-action@master
        with:
          path: "MyProject/"
          type: ".json"

      - name: Output results
        run: |
          echo "Found ${{ steps.pl.outputs.path_count }} file(s) with this extension:"
           echo ${{ steps.pl.outputs.paths[0] }}
          for i in ${{ steps.pl.outputs.paths }}; do
          echo $i
          done
