name: Path lister
on: [push]
jobs:
  list:
    name: Path lister
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v1
      - name: Fetch action
        id: pl
        uses: Rishabh510/Path-lister-action@master
        with:
          path: "MyProject/"
          type: ".json"

      - name: Output results
        run: |
          echo "Found ${{ steps.pl.outputs.path_count }} file(s) with this extension:"
          echo ${{ steps.pl.outputs.paths[1] }}
            echo ${{ steps.pl.outputs.paths[0] }}
          for i in ${{ steps.pl.outputs.paths }}; 
                  do
                     echo $i
                  done
                     
      - name: GetVersionFromJson
        id: version
        uses: lucaspinheirogit/list-from-string-array-action@v1.4.3
        with:
         stringArray: ${{ steps.pl.outputs.paths}}
      - name: Print modified files
        run: echo '${{ steps.modified_files_list.outputs.stringList }}'
      - name: GetVersionFromJson2   
        uses: notiz-dev/github-action-json-property@release
        with: 
           path: '${{ steps.modified_files_list.outputs.stringList }}'
           prop_path: 'projectVersion'
           if: github.ref == 'refs/heads/main'
      - run: echo ${{steps.version.outputs.prop}}
      - name: Version Incrment
        env:
            VERSION: ${{steps.version.outputs.prop}}
        run: |
               $v= [version] "${{steps.version.outputs.prop}}"
               $newversion= "{0}.{1}.{2}.{3}" -f $v.Major, $v.Minor, ($v.Build+1),"${{ steps.current-time.outputs.formattedTime }}"
               $VERSION=[string]$newversion
               echo $VERSION
          
