# This is a basic workflow to help you get UiPath Project to build and Deploy to the intended orchestrator

name: UiPathBuild&Deploy
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:

 remove-old-artifacts:
    runs-on: windows-latest
    timeout-minutes: 10

    steps:
    - name: Remove old artifacts
      uses: c-hive/gha-remove-artifacts@v1
      with:
        age: '1 month'

 BuildandDeploy:
    runs-on: windows-latest
    needs: remove-old-artifacts
    steps:  
      - uses: actions/checkout@v2
      
     # Facilitate the UiPath CLI in the github artifacts
     
      - run: |
                 New-Item -Path "C:\\" -ItemType "directory" -Name "uipathcli";
                 Invoke-WebRequest "https://www.myget.org/F/uipath-dev/api/v2/package/UiPath.CLI/1.0.7758.25166" -OutFile "C:\\uipathcli\\cli.zip";
                 Expand-Archive -LiteralPath "C:\\uipathcli\\cli.Zip" -DestinationPath "C:\\uipathcli"; 
                 
      # Convert to Nuget Package .nupkg using UiPath Cli              
                 
      - name: Build Nuget 
        shell: cmd
        run: |
               call "C:\\uipathcli\\lib\\net461\\uipcli.exe" package pack "${{ github.workspace }}\MyProject" -o "${{ github.workspace }}" -l en-US
      
      #Upload to Github Artifacts for temporary storge memory with retention of 2 days for safety purpose
   
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.0
        with:	 
             name: ProjectFiles
             path: ${{ github.workspace }}/**
             if-no-files-found: error
             retention-days: 2
      - name: Download Artifacts
        uses: actions/download-artifact@v2.0.9
        with:
            name: 'ProjectFiles'
            path: 'ProjectFiles' 
      - name: DeployOrchestrator
        shell: cmd
        run: |
               call "C:\\uipathcli\\lib\\net461\\uipcli.exe" package deploy "${{ github.workspace }}" "https://cloud.uipath.com" default -u sukesh.v@uipath.com -p Nannaamma@10!
     
 
