# This is a basic workflow to help you get started with Actions

name: VersionIncrment

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
 
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: GetVersionFromJson
        id: version
        uses: notiz-dev/github-action-json-property@release
        with: 
           path: '${{ github.workspace }}\MyProject\SFDC\project.json'
           prop_path: 'projectVersion'
           if: github.ref == 'refs/heads/main'
      - run: echo ${{steps.version.outputs.prop}}
      - name: Version Incrment
        env:
            VERSION: ${{steps.version.outputs.prop}}
        run: |
               $v= [version] ${{steps.version.outputs.prop}}.Value 
               $value=[int] $v.Build+1
               echo $value
